In [7]:
import BTClib
import pandas as pd

In [8]:
secret_key = "WqP5txrWtmbGcMND5GjFiBZICth5nZFIXYKEPqKitRl7xOHVGOFzNo8yNCLQUmK4guPTNgV4nwKLT0aD5iYIg"
api_key = "SbyekABHMR0SyrIQKTqU14sExh5m40sV5a6jaBenI26u5SDm8z4gGzQCLamCp6Ww2uJyVjyhJQESk4Gt5jA"
strategy = BTClib.Strategy.THREESOLDIERS
interval = BTClib.Interval.HOURLY_ONEHOUR
bingx_client = BTClib.BingX(api_key=api_key, secret_key=secret_key)

In [12]:
start_time, end_time,intervalAsMillisecond = BTClib.get_times(strategy.value,interval.value)

difference(ms): 14400000
difference(hour): 4.0
number of candles: 3.0
	current interval -> 1h

In [29]:
res = bingx_client.spot.market.get_k_line_data('FRENPET-USDT',interval.value,start_time,end_time,strategy.value)
res

[[1711962000000, 7.1171, 7.1848, 7.1171, 7.1847, 37.0, 1711965599999, 265.83],
 [1711958400000, 7.0478, 7.1172, 6.8717, 7.1171, 69.0, 1711961999999, 485.63],
 [1711954800000,
  7.1636,
  7.2332,
  6.6739,
  7.0478,
  181.0,
  1711958399999,
  1258.24],
 [1711951200000, 7.368, 7.3681, 6.9889, 7.1635, 75.0, 1711954799999, 533.74]]

In [21]:
df = pd.DataFrame(res)
df

,0,1,2,3,4,5,6,7
0,1711962000000,69390.93,69613.61,69390.93,69513.43,63.51,1711965599999,4415474.86
1,1711958400000,69593.84,69595.02,69169.22,69391.36,214.94,1711961999999,14924978.46
2,1711954800000,69612.17,69788.03,69518.54,69596.55,205.97,1711958399999,14348484.91
3,1711951200000,69168.98,69668.81,68888.80,69611.61,315.49,1711954799999,21899447.39

In [22]:
del df[6],df[7]

df.columns = ['time','open','high','low','close','volume']
df

            time      open      high       low     close  volume
0  1711962000000  69390.93  69613.61  69390.93  69513.43   63.51
1  1711958400000  69593.84  69595.02  69169.22  69391.36  214.94
2  1711954800000  69612.17  69788.03  69518.54  69596.55  205.97
3  1711951200000  69168.98  69668.81  68888.80  69611.61  315.49

In [25]:
cdf = df
cdf['isGreen'] = cdf["close"]
cdf['bodyLen'] = abs(cdf["close"] - cdf["open"])

cdf = cdf.reset_index()
del cdf['index']

for i in range(len(cdf)):
    tmp = cdf.loc[i,cdf.columns.values]
    if tmp['open'] <= tmp['close']:
        tmp['isGreen'] = 1
    else:
        tmp['isGreen'] = 0

    cdf.loc[i] = tmp.values

In [26]:
cdf

,time,open,high,low,close,volume,isGreen,bodyLen
0,1711962000000,69390.93,69613.61,69390.93,69513.43,63.51,1.0,122.50
1,1711958400000,69593.84,69595.02,69169.22,69391.36,214.94,0.0,202.48
2,1711954800000,69612.17,69788.03,69518.54,69596.55,205.97,0.0,15.62
3,1711951200000,69168.98,69668.81,68888.80,69611.61,315.49,1.0,442.63

In [28]:
cdf.drop(0,inplace=True)
cdf

,time,open,high,low,close,volume,isGreen,bodyLen
1,1711958400000,69593.84,69595.02,69169.22,69391.36,214.94,0.0,202.48
2,1711954800000,69612.17,69788.03,69518.54,69596.55,205.97,0.0,15.62
3,1711951200000,69168.98,69668.81,68888.80,69611.61,315.49,1.0,442.63